kind: PersistentVolume
apiVersion: v1
metadata:
    name: influxdb-pv
spec:
    storageClassName: local-sc
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/ft_service/InfluxDB"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: influxdb-pvc
    labels:
        app: inf-ptr
spec:
    storageClassName: local-sc
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: influxdb
spec:
    replicas: 1
    selector:
        matchLabels:
            inf-ptr: inf-ptr
    template:
        metadata:
            labels:
                inf-ptr: inf-ptr
        spec:
            volumes:
             - name: influxdb-volume
               persistentVolumeClaim:
                    claimName: influxdb-pvc
            containers:
                - name: influxdb
                  image: influxdb
                  imagePullPolicy: Never
                  livenessProbe:
                    exec:
                        command:
                            - sh
                            - ./lifserv.sh
                    initialDelaySeconds: 10
                    periodSeconds: 5
                  volumeMounts:
                    - mountPath: "/var/lib/influxdb/"
                      name: influxdb-volume
                  ports:
                      - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb-service
spec:
    selector:
        inf-ptr: inf-ptr
    ports:
      - port: 8086
        targetPort: 8086
