kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: mysql-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            mysql-ptr: mysql-ptr
    template:
        metadata:
            labels:
                mysql-ptr: mysql-ptr
        spec:
            volumes:
             - name: mysql-volume
               persistentVolumeClaim:
                    claimName: mysql-pvc
            containers:
                - name: mysql
                  image: mysql
                  imagePullPolicy: Never
                  livenessProbe:
                    exec:
                        command:
                            - sh
                            - ./lifserv.sh
                    initialDelaySeconds: 10
                    periodSeconds: 5
                  volumeMounts:
                    - mountPath: "/var/lib/mysql/"
                      name: mysql-volume
                  ports:
                      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    selector:
        mysql-ptr: mysql-ptr
    ports:
      - port: 3306
        targetPort: 3306
