apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
spec:
    replicas: 1
    selector:
        matchLabels:
            gr-ptr: gr-ptr
    template:
        metadata:
            labels:
                gr-ptr: gr-ptr
        spec:
            containers:
              - name: gr-con
                image: grafana
                imagePullPolicy: Never
                ports:
                    - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
    name: grafana-service
spec:
    type: LoadBalancer
    selector:
        gr-ptr: gr-ptr
    ports:
      - port: 3000
        targetPort: 3000
