apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin
spec:
    replicas: 1
    selector:
        matchLabels:
            php-ptr: php-ptr
    template:
        metadata:
            labels:
                php-ptr: php-ptr
        spec:
            containers:
                - name: phpmyadmin
                  image: phpmyadmin
                  imagePullPolicy: Never
                  livenessProbe:
                    exec:
                        command:
                            - sh
                            - ./lifserv.sh
                    initialDelaySeconds: 10
                    periodSeconds: 5
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
    name: php-service
spec:
    type: LoadBalancer
    selector:
        php-ptr: php-ptr
    ports:
        - port: 5000
          targetPort: 5000
