apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
spec:
    replicas: 1
    selector:
        matchLabels:
            wo-ptr: wo-ptr
    template:
        metadata:
            labels:
                wo-ptr: wo-ptr
        spec:
            containers:
                - name: wordpress
                  image: wordpress
                  imagePullPolicy: Never
                  livenessProbe:
                    exec:
                        command:
                            - sh
                            - ./lifserv.sh
                    initialDelaySeconds: 10
                    periodSeconds: 5
                  ports:
                  - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
    name: wordpress-service
spec:
    type: LoadBalancer
    selector:
        wo-ptr: wo-ptr
    ports:
        - port: 5050
          targetPort: 5050
